---
title: "run.Rmd"
author: "BCM MSPC"
date: '`r Sys.Date()`'
output: html_document
params:
  volcanodir: none
  rankfiledir: none
  species: "Homo sapiens"
  genesets_json: >
    [
      {"category": "H", "subcategory": ""},
      {"category": "C2", "subcategory": "CP:KEGG"},
      {"category": "C2", "subcategory": "CP:REACTOME"},
      {"category": "C5", "subcategory": "GO:MF"},
      {"category": "C5", "subcategory": "GO:BP"},
      {"category": "C5", "subcategory": "GO:CC"}
      /* {"category": "C2", "subcategory": "CP:KEGG"}
      */
    ]

---

# setup

```{r setup, include=TRUE}
library(purrr) # for map()
library(magrittr)
library(ggplot2)
library(fs) # for dir_ls()
library(fgsea)
library(dplyr)
library(msigdbr)
library(stringr)
library(readr)
library(tidyr)
library(tictoc)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, fig.path = 'bcm_gsea_figures')

library(future)
n_cores <- future::availableCores() - 1
future::plan(future::multisession, workers=min(n_cores, 8) )

source("./R/io.R")
source("./R/geneset_utils.R")
source("./R/fgsea.R")
source("./R/plot.R")
```
# explanations

```{r, label=test, eval=F, include=T}
data <- simulate_preranked_data()
geneset <- .GlobalEnv$get_collection("H", "")
geneset_list <- .GlobalEnv$genesets_df_to_list(geneset)
#named_data = list(data=data)
rankobj <- ranks_dfs_to_lists(list(data))

.res <- rankobj[[1]] %>% run_one(geneset_list)
.name <- .res[1, 'pathway'][[1]]

enplot_data <- plotEnrichmentData(geneset_list[[.name]], rankobj[[1]])

.rnkorder <- -rankobj[[1]] %>% (rank)
rankobj[[1]]['rank'] <- .rnkorder

```

## run these to examine what genesets are availabel from msigdbr


```{r, eval=F, include=T}
msigdbr::msigdbr_species()
```

```{r, eval=F, include=T}

msigdbr::msigdbr_collections()
```

# execution

## load gene sets

```{r, label='load params'}

genesets_of_interest <- jsonlite::parse_json(params$genesets_json)
species <- params$species

#SPECIES <- "Homo sapiens" # or "Mus musculus" or Saccharomyces cerevisiae, and others
# genesets_of_interest %>% purrr::map(~{print(.x$category); print(.x$subcategory)})

```


```{r, label='get genesets'}
list_of_geneset_dfs <- genesets_of_interest %>% .GlobalEnv$get_collections()
geneset_lists <- list_of_geneset_dfs %>% purrr::imap( ~.GlobalEnv$genesets_df_to_list(.x) )
```

```{r, label='convert geneset objects'}
pathways_list_of_lists <-
  list_of_geneset_dfs %>% purrr::map(.GlobalEnv$genesets_df_to_list)
```



## prepare ranks

```{r, label='load ranks'}

if ( (!file.exists(params$volcanodir)) &
     (!file.exists(params$rankfiledir))
){
  print("no files present")
  knitr::knit_exit()
}

```



```{r, label='prepare ranks'}

rankfiledir <- params$rankfiledir
volcanodir <- params$volcanodir
if ( length(fs::dir_ls(rankfiledir, fail=F))==0 ){
  #print('yes')
  rnkdfs <- .GlobalEnv$create_rnkfiles(volcanodir, value_col = "signedlogP")
  rnkdfs %>% .GlobalEnv$write_rnkfiles(dir = rankfiledir)
} #else{

# always reload rank files from new location to ensure proper format
# any format / name issues are fixed in the create_rnkfiles func
rnkfiles <- dir_ls(rankfiledir, pattern = ".rnk$", fail=F) 
rnkdfs <- rnkfiles %>% .GlobalEnv$load_rnkfiles()
  #print('no')
#}

ranks_list <- rnkdfs %>% .GlobalEnv$ranks_dfs_to_lists()
ranks_list <- rnkdfs %>% map(
  ~ with(.x, setNames(value, geneid))
)

# rnkdfs %>% str()
```


# run fgsea
```{r, label='run fgsea'}

results_list <- .GlobalEnv$run_all_pathways(pathways_list_of_lists, ranks_list)

(results_list)
```






```{r}
names(results_list)
```
```{r}
names(results_list[[1]])
```

```{r}
names(results_list[[1]] [[1]] )
```





```{r}
results_list[[1]] [[1]] %>% 
  arrange(pval) %>% 
  head(20) %>% 
  .GlobalEnv$barplot_with_numbers()
```

```{r}
results_list[[1]] %>% imap(
  ~ {
    sel <- .x %>% arrange(pval) %>% head(20)
    .title <- .y %>% fs::path_file() %>% fs::path_ext_remove() #%>% gsub(pattern="_", replacement=" ", x=.)
    .GlobalEnv$barplot_with_numbers(sel, title=.y, use_custom_labeller=T)
  }
)
```


```{r, fig.width=12, fig.height=12}


results_list %>% 
  .GlobalEnv$process_results_across_rnks()


```



```{r, fig.width=10, fig.height=12}

tic()

process_results_for_each_rank <- function(results_list, ranks_list, pathways_list) {
  # Ensure names are aligned and iterate over them
  pathway_names <- names(results_list)
  
  map(pathway_names, ~{
    geneset_name <- .x
    fgsea_res_list <- results_list[[geneset_name]]
    genesets <- pathways_list[[geneset_name]]
    
    # Now, iterate over each rank file within this pathway category
    map(names(ranks_list), function(rank_name) {
      rankobj <- ranks_list[[rank_name]]
      # Generate a unique identifier for this plot/table, e.g., combining pathway name and rank file name
      rank_name_nice <- rank_name %>% fs::path_file() %>% fs::path_ext_remove()
      plot_id <- paste(geneset_name, rank_name_nice, sep = "_")
      
      
      .fgsea_res <- fgsea_res_list[[rank_name]]
      p <- plot_table(fgsea_res = .fgsea_res,
                 ranks = rankobj,
                 pathways = genesets,
                 gsea_param=0.5,
        )
      
      outpath <- file.path(ENPLOT_BASEDIR, make.names(geneset_name), make.names(rank_name_nice))
      if (!fs::dir_exists(outpath)) fs::dir_create(outpath)
      
      # print(p)
      return(p)
      
      # c(".png", ".pdf") %>% purrr::walk(
      # ~ggsave(filename = paste0(make.names(geneset_name), "_toptable", "_gseaparam.5", .x),
      #        path = outpath,
      #        dpi = 300,
      #        width = 19,
      #        height=12,
      #        ) 
      # )
      
      
    })
    
  })
}

res <- process_results_for_each_rank(
  results_list = results_list,
  ranks_list = ranks_list,
  pathways_list = geneset_lists
)

toc()

```


```{r, fig.width=10, fig.height=12}

tic()

process_results_for_each_rank <- function(results_list, ranks_list, pathways_list) {
  # Ensure names are aligned and iterate over them
  pathway_names <- names(results_list)
  
  # furrr::future_map(pathway_names, ~{
  purrr::map(pathway_names, ~{
    geneset_name <- .x
    fgsea_res_list <- results_list[[geneset_name]]
    genesets <- pathways_list[[geneset_name]]
    
    # Now, iterate over each rank file within this pathway category
    #map(names(ranks_list), function(rank_name) {
    # furrr::future_map(names(ranks_list), function(rank_name) {
    furrr::future_imap(ranks_list, function(rankobj, rank_name) {
      # rankobj <- ranks_list[[rank_name]]
      # Generate a unique identifier for this plot/table, e.g., combining pathway name and rank file name
      rank_name_nice <- rank_name %>% fs::path_file() %>% fs::path_ext_remove()
      plot_id <- paste(geneset_name, rank_name_nice, sep = "_")
      
      
      .fgsea_res <- fgsea_res_list[[rank_name]]
      p <- plot_table(fgsea_res = .fgsea_res,
                 ranks = rankobj,
                 pathways = genesets,
                 gsea_param=0.5,
        )
      
      outpath <- file.path(ENPLOT_BASEDIR, make.names(geneset_name), make.names(rank_name_nice))
      if (!fs::dir_exists(outpath)) fs::dir_create(outpath)
      
      # print(p)
      return(p)
      # c(".png", ".pdf") %>% purrr::walk(
      # ~ggsave(filename = paste0(make.names(geneset_name), "_toptable", "_gseaparam.5", .x),
      #        path = outpath,
      #        dpi = 300,
      #        width = 19,
      #        height=12,
      #        ) 
      # )
      
      
    })
    
  })
}

res <- process_results_for_each_rank(
  results_list = results_list,
  ranks_list = ranks_list,
  pathways_list = geneset_lists
)

toc()

#76.388
```




```{r}
ranks_list %>% names
list_of_geneset_dfs %>% names

.res <- .GlobalEnv$get_rankorder(ranks_list[[1]], geneset_lists[[1]][[1]]  )

enplot_data <- plotEnrichmentData(geneset_lists$H_$HALLMARK_ADIPOGENESIS, ranks_list[[1]]) 

```


```{r}

p <- plotEnrichment(geneset_lists$H_$HALLMARK_ADIPOGENESIS, ranks_list[[1]]) 
p
```


```{r}
.res %>% head
```


```{r}


.res %>% filter(!is.na(stat_tick))  %>% 
  left_join(list_of_geneset_dfs$H_ %>% mutate(entrez_gene = as.character(entrez_gene)), by = c('id' = 'entrez_gene')) %>% 
  edgeplot1() +
  geom_text(data = . %>% arrange(rank) %>% head(10), aes(label = gene_symbol )  )
  
```


