[params]
volcanodir = '' # use single quote for specifying paths
rankfiledir = ''
gct_path = ""
ranks_from = ""  # choices are volcano and gct
species = "Homo sapiens"
savedir = ""
zscore_emat = true
zscore_emat_groupby = false #
cut_by = "group"

[params.barplot]
limit = "auto"
do_individual = true
do_combined = true

[params.bubbleplot]
limit = "auto"
do_individual = true
do_combined = true

[params.enplot]
do = true
limit = 10
do_individual = true
do_combined = true
combine_by = false

[params.heatmap_gsea]
do = true
limit = 10

[params.heatmap_gene]
do = true
limit = 10

[params.pca]
width = 7.8
height = 7.4
col_by = ""
mark_by = ""

[params.extra]
rankname_order = []
samplename_order = []
#
# Custom colormap for heatmap annotations (discrete metadata)
# Provide a JSON file path relative to the run root. Example:
# colormap_file = "config/colormap.json"
#
# Supported JSON formats:
#
# 1) Object with global and by_column maps
# {
#   "global": { "Responder": "#4DAF4A", "NonResponder": "#984EA3" },
#   "by_column": {
#     "group": { "Treated": "#E41A1C", "Control": "#377EB8" },
#     "batch": { "BatchA": "#1B9E77", "BatchB": "#D95F02" }
#   }
# }
#
# 2) Array of entries (column is optional; without it, entry is global)
# [
#   {"column": "group", "name": "Treated", "color": "#E41A1C"},
#   {"column": "group", "name": "Control", "color": "#377EB8"},
#   {"name": "Responder", "color": "#4DAF4A"}
# ]
#
# Notes:
# - Colors should be hex like #1F77B4 (named R colors also work).
# - Matching is exact and case sensitive for both column and name.
# - Only discrete annotations use explicit mappings. Numeric/decimal
#   columns are shown with continuous gradients and ignore mappings.
# - TSV/CSV (2 or 3 columns) is also supported for backward compatibility.

[[params.genesets]]
category = "H"
subcategory = ""
collapse = false

[[params.genesets]]
category = "C2"
subcategory = "CP:KEGG"
collapse = true

[[params.genesets]]
category = "C2"
subcategory = "CP:REACTOME"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "GO:MF"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "GO:BP"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "GO:CC"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "All"
collapse = true

[params.advanced]
parallel = true
cache = true
replace = true
cachedir = "savedir"
logfile = "savedir"
loglevel = "INFO"
