[params]
ranks_from = ""  # choices are volcano and gct. must specify this
savedir = '' # this is the base directory all results will be saved within. paths are relative from where program is executed
volcanodir = '' # use single quote for specifying paths
rankfiledir = "savedir" # "savedir" special character string indicating to save rankfiles within the specified savedir
gct_path = ''
species = "Homo sapiens"  # Mus musculus, ..
zscore_emat = true
zscore_emat_groupby = false # change this to a metadata variable to zscore within. otherwise leave false
cut_by = "group"

[params.barplot]
limit = [12, 20, 32]
do_individual = true
do_combined = true
  [params.barplot.advanced]
  stroke_width = 1.0

[params.bubbleplot]
limit = [12, 20, 32]
do_individual = true
do_combined = true
glyph = "⁕"
  [params.bubbleplot.advanced]
  stroke_width = 0.8
  stroke_alpha = 0.55

[params.enplot]
do_individual = true
do_combined = true
limit = 10
combine_by = false

[params.heatmap_gsea]
do = true
limit = [10, 20, 40, 80]  # will plot each size

[params.heatmap_gene]
do = true
limit = 10

[params.pca]
do = false
width = 7.8
height = 7.4
col_by = ""
mark_by = ""

[params.extra]
rankname_order = []
samplename_order = []

[[params.genesets]]
category = "H"
subcategory = ""
collapse = false

[[params.genesets]]
category = "C2"
subcategory = "CP:KEGG"
collapse = true

[[params.genesets]]
category = "C2"
subcategory = "CP:REACTOME"
collapse = true

[[params.genesets]]
category = "C3"
subcategory = "TFT:GTRD"
collapse = true

[[params.genesets]]
category = "C3"
subcategory = "MIR:MIRDB"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "GO:MF"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "GO:BP"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "GO:CC"
collapse = true

[[params.genesets]]
category = "C5"
subcategory = "All"
collapse = true


[[params.genesets]]
category = "C6"
subcategory = ""
collapse = true #

[[params.genesets]]
category = "C7"
subcategory = "IMMUNESIGDB"
collapse = true



[params.advanced]
parallel = true
cache = true
replace = false
cachedir = "savedir"
logfile = "savedir"
loglevel = "INFO"
pivot_gsea_results = false
